### PR TITLE
add description for cluster self service

### PR DESCRIPTION
**Pull request by dherbrich**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dherbrich Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=cf-platform-eng/isv-docs&pullRequestId=26)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=cf-platform-eng/isv-docs&pullRequestId=26) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dherbrich Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=cf-platform-eng/isv-docs&pullRequestId=26)!

**Comment by tehall16** [comment]
Thanks Peter!  @dherbrich If it's possible to obscure it I think that would be best.

**Comment by dherbrich** [comment]
i removed the name from the image.

**Pull request merged**
